# This file is machine-generated - editing it directly is not advised

[[AbstractAlgebra]]
deps = ["InteractiveUtils", "LinearAlgebra", "Markdown", "Random", "RandomExtensions", "SparseArrays", "Test"]
git-tree-sha1 = "139bade4dd5b48c6caa9eba3d8d7d67096aa145f"
uuid = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
version = "0.13.3"

[[Antic_jll]]
deps = ["Artifacts", "FLINT_jll", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "Pkg"]
git-tree-sha1 = "ba62a46311df2d510f689621cb133513153a8bd5"
uuid = "e21ec000-9f72-519e-ba6d-10061e575a27"
version = "0.200.300+0"

[[Arb_jll]]
deps = ["Artifacts", "FLINT_jll", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "Pkg"]
git-tree-sha1 = "2474be8e6c694c8977cca9f9a3ad075531ddb486"
uuid = "d9960996-1013-53c9-9ba4-74a4155039c3"
version = "200.1900.0+0"

[[Artifacts]]
deps = ["Pkg"]
git-tree-sha1 = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744"
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
version = "1.3.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinaryProvider]]
deps = ["Libdl", "Logging", "SHA"]
git-tree-sha1 = "ecdec412a9abc8db54c0efc5548c64dfce072058"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.10"

[[CompilerSupportLibraries_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "8e695f735fca77e9708e795eda62afdb869cbb70"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version = "0.3.4+0"

[[Conda]]
deps = ["JSON", "VersionParsing"]
git-tree-sha1 = "c0647249d785f1d5139c0cc96db8f6b32f7ec416"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "1.5.0"

[[CxxWrap]]
deps = ["Libdl", "MacroTools", "libcxxwrap_julia_jll"]
git-tree-sha1 = "95196cd23b6135d92079a6de33e1d522cc4cd2a4"
uuid = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
version = "0.11.2"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DocStringExtensions]]
deps = ["LibGit2", "Markdown", "Pkg", "Test"]
git-tree-sha1 = "50ddf44c53698f5e784bbebb3f4b21c5807401b1"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.8.3"

[[FLINT_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "Pkg"]
git-tree-sha1 = "648891e837baafba25dd81a129fbef9b1f191d47"
uuid = "e134572f-a0d5-539d-bddf-3cad8db41a82"
version = "200.700.0+0"

[[FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[GAP]]
deps = ["GAP_jll", "GAP_lib_jll", "Libdl", "Markdown", "Pkg", "REPL", "Random"]
git-tree-sha1 = "adf168fb16b9e2f28c53c2334cd53ac7f16d0af7"
uuid = "c863536a-3901-11e9-33e7-d5cd0df7b904"
version = "0.5.2"

[[GAP_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg", "Readline_jll", "Zlib_jll"]
git-tree-sha1 = "8ee307bdc41e63d3bf18c4fca98d2ecf52e8a13a"
uuid = "5cd7a574-2c56-5be2-91dc-c8bc375b9ddf"
version = "400.1100.1+0"

[[GAP_lib_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "e05c6c8bd8422e373adf770b9f8f433e49c525cf"
uuid = "de1ad85e-c930-5cd4-919d-ccd3fcafd1a3"
version = "400.1100.0+0"

[[GLPK_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9b717ca4e967fad6b8b6071f4cca1f9593a66499"
uuid = "e8aa6df9-e6ca-548a-97ff-1f85fc5b8b98"
version = "4.65.0+1"

[[GMP_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "15abc5f976569a1c9d651aff02f7222ef305eb2a"
uuid = "781609d7-10c4-51f6-84f2-b8444358ff6d"
version = "6.1.2+6"

[[Gettext_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "8c14294a079216000a0bdca5ec5a447f073ddc9d"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.20.1+7"

[[Hecke]]
deps = ["AbstractAlgebra", "Dates", "Distributed", "InteractiveUtils", "Libdl", "LinearAlgebra", "Markdown", "Nemo", "Pkg", "Printf", "Profile", "Random", "RandomExtensions", "Requires", "Serialization", "SparseArrays", "Test"]
git-tree-sha1 = "5e69e26180a4ce3b70447d7d0e7dbe7abd8e6798"
uuid = "3e1990a7-5d81-5526-99ce-9ba3ff248f21"
version = "0.9.4"

[[IJulia]]
deps = ["Base64", "Conda", "Dates", "InteractiveUtils", "JSON", "Markdown", "MbedTLS", "Pkg", "Printf", "REPL", "Random", "SoftGlobalScope", "Test", "UUIDs", "ZMQ"]
git-tree-sha1 = "0862f73c51b49d80168e75b141a26d1cbb9a7295"
uuid = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
version = "1.23.1"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JLLWrappers]]
git-tree-sha1 = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.2.0"

[[JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "81690084b6198a2e1da36fcfda16eeca9f9f24e4"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.1"

[[LZO_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "f128cd6cd05ffd6d3df0523ed99b90ff6f9b349a"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.0+3"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libiconv_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "8e924324b2e9275a51407a4e06deb3455b1e359f"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.0+7"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[LoadFlint]]
deps = ["BinaryProvider", "FLINT_jll", "GMP_jll", "Libdl", "MPFR_jll", "Pkg"]
git-tree-sha1 = "46f13846aef516148d48ec8a708a1055530d6856"
uuid = "472f376f-f1cf-461b-9ac1-d103423be9b7"
version = "0.5.0"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[MPFR_jll]]
deps = ["GMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "301ce96952df90bbaa2c66112b7c1f15ced2b55b"
uuid = "3a97d323-0669-5f0c-9066-3539efd106a3"
version = "4.1.0+1"

[[MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "6a8a2a625ab0dea913aba95c11370589e0239ff0"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.6"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[MbedTLS]]
deps = ["Dates", "MbedTLS_jll", "Random", "Sockets"]
git-tree-sha1 = "1c38e51c3d08ef2278062ebceade0e46cefc96fe"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "1.0.3"

[[MbedTLS_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6"
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
version = "2.16.8+1"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[MongoC_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "OpenSSL_jll", "Pkg", "Zlib_jll", "Zstd_jll", "snappy_jll"]
git-tree-sha1 = "85c5435f7f7bc3930f843e7dd5c0d48c9d8aa5ea"
uuid = "90100e71-7732-535a-9be7-2e9affd1cfc1"
version = "1.16.2+1"

[[Mongoc]]
deps = ["Dates", "MongoC_jll", "Serialization"]
git-tree-sha1 = "d5b83f03ea94cafe6a7ed5440a8100beed569628"
uuid = "4fe8b98c-fc19-5c23-8ec2-168ff83495f2"
version = "0.6.1"

[[MozillaCACerts_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "bbcac5afd9049834366c3b68d792971e3d981799"
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"
version = "2020.10.14+0"

[[Ncurses_jll]]
deps = ["Artifacts", "Gettext_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "1c200bf08f1646f8e5c8fb81ca10e41e9516619a"
uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
version = "6.1.0+5"

[[Nemo]]
deps = ["AbstractAlgebra", "Antic_jll", "Arb_jll", "BinaryProvider", "FLINT_jll", "InteractiveUtils", "Libdl", "LinearAlgebra", "LoadFlint", "Markdown", "Pkg", "Random", "RandomExtensions", "SHA", "Test"]
git-tree-sha1 = "458daff5e44ba1890eda15f19481b5fe9e1d7fd2"
uuid = "2edaba10-b0f1-5616-af89-8c11ac63239a"
version = "0.20.0"

[[Ninja_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "fd9302c04a8a7331a8a1628b8b8127d52f69b142"
uuid = "76642167-d241-5cee-8c94-7a494e8cb7b7"
version = "1.10.2+0"

[[OpenSSL_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "71bbbc616a1d710879f5a1021bcba65ffba6ce58"
uuid = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
version = "1.1.1+6"

[[Oscar]]
deps = ["AbstractAlgebra", "DocStringExtensions", "GAP", "Hecke", "LinearAlgebra", "Markdown", "Nemo", "Pkg", "Polymake", "Random", "RandomExtensions", "Requires", "Singular", "Test"]
git-tree-sha1 = "501602b8c0efc9b4fc6a68d0cb53b9103f736313"
repo-rev = "d0908f50a28c46be231ce84fecfac9d2dee3ee47"
repo-url = "https://github.com/oscar-system/Oscar.jl"
uuid = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
version = "0.5.1"

[[PPL_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "d9be9ffc4e9a88d0d67663e8cb11611ac4b38e91"
uuid = "80dd9cbb-8b87-5171-a280-372cc418f402"
version = "1.2.0+1"

[[Parsers]]
deps = ["Dates"]
git-tree-sha1 = "50c9a9ed8c714945e01cd53a21007ed3865ed714"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "1.0.15"

[[Perl_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Readline_jll"]
git-tree-sha1 = "f05b5f1ef1dde52d993069f5738263c422f40817"
uuid = "83958c19-0796-5285-893e-a1267f8ec499"
version = "5.30.3+2"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Polymake]]
deps = ["CxxWrap", "FLINT_jll", "JSON", "Libdl", "Markdown", "Mongoc", "MozillaCACerts_jll", "Ninja_jll", "Perl_jll", "Pkg", "REPL", "SparseArrays", "libpolymake_julia_jll", "polymake_jll"]
git-tree-sha1 = "195e1dc7d868715665dc8723044917c0fba505ac"
uuid = "d720cf60-89b5-51f5-aff5-213f193123e7"
version = "0.5.5"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Profile]]
deps = ["Printf"]
uuid = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RandomExtensions]]
deps = ["Random", "SparseArrays"]
git-tree-sha1 = "062986376ce6d394b23d5d90f01d81426113a3c9"
uuid = "fb686558-2515-59ef-acaa-46db3789a887"
version = "0.4.3"

[[Readline_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Ncurses_jll", "Pkg"]
git-tree-sha1 = "09fe5d025684bee7fa5da3d2048a09558cdf4b9d"
uuid = "05236dd9-4125-5232-aa7c-9ec0c9b2c25a"
version = "8.0.4+1"

[[Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "cfbac6c1ed70c002ec6361e7fd334f02820d6419"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.1.2"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Singular]]
deps = ["AbstractAlgebra", "CxxWrap", "LinearAlgebra", "Markdown", "Nemo", "Pkg", "Random", "RandomExtensions", "Singular_jll", "Statistics", "lib4ti2_jll", "libsingular_julia_jll"]
git-tree-sha1 = "b4400eb8df84cb74b30d848b7b8835251d70a05a"
uuid = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"
version = "0.4.5"

[[Singular_jll]]
deps = ["Artifacts", "FLINT_jll", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "Pkg", "cddlib_jll"]
git-tree-sha1 = "23bdd84bbccadf92ae56ab632e1ed4f9462f97b1"
uuid = "43d676ae-4934-50ba-8046-7a96366d613b"
version = "402.0.101+0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SoftGlobalScope]]
deps = ["REPL"]
git-tree-sha1 = "986ec2b6162ccb95de5892ed17832f95badf770c"
uuid = "b85f4697-e234-5449-a836-ec8e2f98b302"
version = "1.1.0"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VersionParsing]]
git-tree-sha1 = "80229be1f670524750d905f8fc8148e5a8c4537f"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.2.0"

[[XML2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "be0db24f70aae7e2b89f2f3092e93b8606d659a6"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.9.10+3"

[[ZMQ]]
deps = ["FileWatching", "Sockets", "ZeroMQ_jll"]
git-tree-sha1 = "fc68e8a3719166950a0f3e390a14c7302c48f8de"
uuid = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
version = "1.2.1"

[[ZeroMQ_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "libsodium_jll"]
git-tree-sha1 = "74a74a3896b63980734cc876da8a103454559fe8"
uuid = "8f1865be-045e-5c20-9c9f-bfbfb0764568"
version = "4.3.2+6"

[[Zlib_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "320228915c8debb12cb434c59057290f0834dbf6"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.11+18"

[[Zstd_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "2c1332c54931e83f8f94d310fa447fd743e8d600"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.4.8+0"

[[bliss_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "efa0ae50a40cdf404e18ce375dfb764001f38b92"
uuid = "508c9074-7a14-5c94-9582-3d4bc1871065"
version = "0.73.0+1"

[[boost_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "95bda308f7f69473c3c98b0cf4cf19e19a88cd49"
uuid = "28df3c45-c428-5900-9ff8-a3135698ca75"
version = "1.71.0+3"

[[cddlib_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "61b6618e9ab74115e13168b85b8e73cbfee6a078"
uuid = "f07e07eb-5685-515a-97c8-3014f6152feb"
version = "0.94.10+1"

[[lib4ti2_jll]]
deps = ["Artifacts", "GLPK_jll", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b4c0837bdc2663b11a6cd1a542bc67bb50a56ae3"
uuid = "1493ae25-0f90-5c0e-a06c-8c5077d6d66f"
version = "1.6.9+2"

[[libcxxwrap_julia_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "48b83f1eb1349f7389dd5bbe4f90eb8534ed5336"
uuid = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
version = "0.8.5+1"

[[libpolymake_julia_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Pkg", "libcxxwrap_julia_jll", "polymake_jll"]
git-tree-sha1 = "ee5ee6cca1a31f4d8afa86bbb5a5a135a0f566fc"
uuid = "4d8266f6-2b3b-57e3-ad7a-d431eaaac945"
version = "0.4.5+0"

[[libsingular_julia_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Singular_jll", "libcxxwrap_julia_jll"]
git-tree-sha1 = "826e36bb99d98170919087ad16c620810ab05b95"
uuid = "ae4fbd8f-ecdb-54f8-bbce-35570499b30e"
version = "0.8.5+0"

[[libsodium_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7127f5f40332ccfa43ee07dcd0c4d81a27d9bb23"
uuid = "a9144af2-ca23-56d9-984f-0d03f7b5ccf8"
version = "1.0.18+1"

[[lrslib_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "cd313aaa89044a7f94a39a1f56803a449816bd74"
uuid = "3873f7d0-7b7c-52c3-bdf4-8ab39b8f337a"
version = "0.1.0+2"

[[nauty_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "3159227bc7a0c2278ef14c71ffc16590c8319407"
uuid = "55c6dc9b-343a-50ca-8ff2-b71adb3733d5"
version = "2.6.12+1"

[[normaliz_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "FLINT_jll", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "Pkg", "nauty_jll"]
git-tree-sha1 = "9095c5ccadc7128cf80cc413a80e40d3251f919d"
uuid = "6690c6e9-4e12-53b8-b8fd-4bffaef8839f"
version = "300.800.900+0"

[[polymake_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "FLINT_jll", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "PPL_jll", "Perl_jll", "Pkg", "bliss_jll", "boost_jll", "cddlib_jll", "lrslib_jll", "normaliz_jll"]
git-tree-sha1 = "3bf841a6aab7aa10474f13dffce150176ae802b2"
uuid = "7c209550-9012-526c-9264-55ba7a78ba2c"
version = "400.300.0+1"

[[snappy_jll]]
deps = ["Artifacts", "JLLWrappers", "LZO_jll", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "d0a0709cb12b85db3e44bfef69f0a68ac7a8c426"
uuid = "fe1e1685-f7be-5f59-ac9f-4ca204017dfd"
version = "1.1.8+1"
